name: scrape
on:
  schedule:
    - cron: "38 */2 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      -
        name: Install Packages
        run: |
          python3 -m pip install -r requirements.txt
      -
        name: Do stuff
        run: |
          python main.py || echo "failed, doing nothing"
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add . && git commit -m 'Update: '"$(date)" && git push || echo "failed, commit nothing"
      -
        name: Say Goodbye
        run: echo "Goodbye!"

